Module6 task1
htmlacademy-php/899487-readme-12 pull request #10
Opened 2021-08-09 08:23 UTC by rudserg39

2021-08-12 13:27 UTC, dshemin requested changes

2021-08-12 13:27 UTC, dshemin commented on index.php
> +$getId = $_GET['id'];
Создайте файлик `post.php` и поместите работу с постами туда, как сказано в задании. Чтобы потом проверить как работают просты достаточно в браузере к хосту добавить `/post.php?id=1`.

2021-08-26 08:49 UTC, alexpalyan requested changes

2021-08-26 08:49 UTC, alexpalyan commented on post.php
> +    LIMIT 6
Этот участок почти 1 в 1 повторяет блок кода из index.php за исключением того что еще тут добавляется условие по posts.id
предлагаю этот код вынести в отдельную функцию, где на вход принимать параметром posts.id и если он пустой то просто не добавлять это условие  )

так же вижу еще один такой блок в index.php, только там с условием по content_types.id
аналогично лучше реализовать передачу, допустим параметром функции. можно сделать более универсально - передавать параметром условие

2021-08-26 08:49 UTC, alexpalyan commented on post.php
> +    WHERE posts.id = '{$getId}'
$getId не проверяется и никак не обрабатывается, что недопустимо. Прочитай пожалуйста главу учебника про SQL инъекцию: https://up.htmlacademy.ru/php/12/book/5.3

2021-08-28 15:56 UTC, freedayko requested changes

2021-08-28 15:56 UTC, freedayko commented on db-data.php
> +            WHERE $condition
Уже гораздо лучше ) посмотри, этот запрос отличается от запроса ниже только этой строчкой. мы можем собрать запрос отдельно в строку и под условие положить только эту строчку?

2021-08-28 15:56 UTC, freedayko commented on index.php
> +$condition = $getId ? "content_types.id = '{$getId}'" : false;
в sql попадает необработанный пользовательский ввод. Посмотри пожалуйста главу об SQL инъекциях в учебнике https://up.htmlacademy.ru/php/12/book/5.3

2021-08-28 15:56 UTC, freedayko commented on post.php
> +require_once('./db-data.php');
Где обработка входящего параметра? Где логика?
страница просмотра публикации должна открываться по адресу http://localhost/post.php?id=1 (1 - или другой целочисленный ID существующей публикации)

2021-09-07 17:49 UTC, freedayko requested changes

2021-09-07 17:49 UTC, freedayko commented on add.php
> +        'contentTypes' => $contentTypes,
Не видно откуда взялась $contentTypes
и отсутствует обработчик добавления

2021-09-07 17:49 UTC, freedayko commented on db-data.php
> +require_once('./helpers.php');
Используется ли что-либо из helpers.php в db-data.php? если нет, то эту строчку нужно убрать отсюда и разместить в основных сценариях

2021-09-07 17:49 UTC, freedayko commented on post.php
> +function getPost($connection, $getId)
Нужно функции из этого файла в файл с функциями (например, functions.php или db-data.php)

2021-09-18 04:38 UTC, merged